# Generated by Django 2.0 on 2019-10-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reader', '0001_initial'),
        ('book', '0002_auto_20190927_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete='CASCADE', to='book.Book')),
                ('reader', models.ForeignKey(on_delete='CASCADE', to='reader.Reader_Profile')),
            ],
        ),
    ]
