# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-26 01:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=108, verbose_name='书名')),
                ('introduction', models.CharField(default='', max_length=1000, verbose_name='简介')),
                ('classification', models.IntegerField(default=0, verbose_name='分类')),
                ('image', models.ImageField(upload_to='', verbose_name='头像')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_forbid', models.BooleanField(default=False, verbose_name='是否被禁')),
                ('click_volume', models.IntegerField(default=0, verbose_name='点击量')),
                ('like_volume', models.IntegerField(default=0, verbose_name='点赞量')),
                ('is_end', models.BooleanField(default=0, verbose_name='是否完结')),
                ('word_count', models.IntegerField(default=0, verbose_name='字数')),
                ('collection_amount', models.IntegerField(default=0, verbose_name='收藏量')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.Author')),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
