# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-26 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
    ]
