# Generated by Django 2.0 on 2019-09-27 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0002_auto_20190926_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='book',
            field=models.ForeignKey(on_delete='CASCADE', to='book.Book'),
        ),
    ]
