# Generated by Django 2.0 on 2019-10-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reader', '0001_initial'),
        ('book', '0002_auto_20190927_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('parent_comment', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete='CASCADE', to='book.Book')),
                ('reader', models.ForeignKey(on_delete='CASCADE', related_name='评论者', to='reader.Reader_Profile')),
                ('to_whom', models.ForeignKey(null=True, on_delete='CASCADE', related_name='评论谁', to='reader.Reader_Profile')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
